# Site settings
title: MelodyTown
email: kibongatsho31@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://mulondaej.github.io/melodytown" # the subpath of your site, e.g. /blog/
url: "https://mulondaej.github.io/melodytown" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

<<<<<<< HEAD
thrmr: jekyll-theme-minimal
=======
theme: jekyll-theme-minimal
>>>>>>> addeaf8831de54dfbb692e9ab39a806c13055a8e
